name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install PlatformIO Libraries
      run: pio lib install
    - name: Clear SD Library
      run: find .pio -name "SD" -exec rm -rf {} \; || true
    - name: Run PlatformIO Build
      run: pio run -e d1_mini
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: firmware.bin
        path: .pio/build/d1_mini/firmware.bin
